name: Deploy to Scaleway

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  REGISTRY: rg.fr-par.scw.cloud
  NAMESPACE: ${{ secrets.SCW_REGISTRY_NAMESPACE }}
  IMAGE_NAME: velib-mcp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Scaleway Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: nologin
        password: ${{ secrets.SCW_SECRET_KEY }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to Scaleway Container
      env:
        SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
        SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
        SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
        SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
        SCW_DEFAULT_REGION: fr-par
        SCW_DEFAULT_ZONE: fr-par-1
      run: |
        # Install Scaleway CLI
        curl -o /tmp/scw -L "https://github.com/scaleway/scaleway-cli/releases/latest/download/scaleway-cli_linux_amd64"
        sudo install /tmp/scw /usr/local/bin/scw
        
        # Deploy to Scaleway Serverless Containers
        CONTAINER_NAME="velib-mcp"
        IMAGE_TAG="${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:main"
        
        # Check if container exists
        if scw container container list name=${CONTAINER_NAME} -o json | jq -e '.[] | select(.name=="'${CONTAINER_NAME}'")' > /dev/null; then
          echo "Updating existing container..."
          CONTAINER_ID=$(scw container container list name=${CONTAINER_NAME} -o json | jq -r '.[0].id')
          scw container container update ${CONTAINER_ID} registry-image=${IMAGE_TAG}
          scw container container deploy ${CONTAINER_ID}
        else
          echo "Creating new container..."
          scw container container create \
            name=${CONTAINER_NAME} \
            registry-image=${IMAGE_TAG} \
            port=8080 \
            min-scale=0 \
            max-scale=1 \
            memory-limit=512 \
            cpu-limit=1000
        fi